# Generated by Django 5.1.1 on 2024-10-02 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('query', models.CharField(max_length=255, verbose_name='查询内容')),
                ('result_ids', models.JSONField(verbose_name='匹配到的段落ID列表')),
                ('result_contents', models.JSONField(verbose_name='匹配到的段落内容列表')),
                ('method', models.CharField(max_length=100, verbose_name='使用的方法')),
                ('project_id', models.IntegerField(verbose_name='所属项目ID')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
