# Generated by Django 5.1.1 on 2024-10-23 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_result_contents_report_paragraph_contents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('query', models.CharField(max_length=255, verbose_name='查询内容')),
                ('doc_id', models.IntegerField(verbose_name='匹配到的文章ID')),
                ('doc_name', models.CharField(max_length=255, verbose_name='匹配到的文章标题')),
                ('paragraph_id', models.IntegerField(verbose_name='匹配到的段落ID')),
                ('paragraph_title', models.CharField(max_length=255, verbose_name='匹配到的段落标题')),
                ('paragraph_content', models.TextField(verbose_name='匹配到的段落内容')),
                ('method', models.CharField(max_length=100, verbose_name='使用的方法')),
                ('project_id', models.IntegerField(verbose_name='所属项目ID')),
            ],
            options={
                'db_table': 'report2',
            },
        ),
    ]
